WebApplication2/Models/Genre.cs
namespace WebApplication2.Models
{
    public class Genre
    {
        public int GenreId { get; set; }
        public string Name { get; set; }
    }
}

WebApplication2/Models/HomePageViewModel.cs
namespace WebApplication2.Models
{
    public class HomePageViewModel
    {
        public List<Movie> PopularMovies { get; set; }
    }
}

WebApplication2/Models/Movie.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication2.Models
{
    public class Movie
    {
        public int MovieId { get; set; }
        [Required(ErrorMessage ="Başlık Kısmı Boş Olamaz!!!")]
        [StringLength(40,MinimumLength =1,ErrorMessage ="Başlık Kısmı 1-40 Karakter Arasında Olmalıdır!!!")]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string Director { get; set; }
        public string[] Players { get; set; }
        [Required]
        public string ImgUrl { get; set; }
        [Required]
        public int? GenreId { get; set; }
    }
}

WebApplication2/Models/MoviesViewModel.cs
namespace WebApplication2.Models
{
    public class MoviesViewModel
    {
        public List<Movie> Movies { get; set; }
       
    }
}

WebApplication2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var model = new HomePageViewModel
            {
                PopularMovies = MovieRepository.Movies
            };
            return View(model);
        }
        public IActionResult About()
        {
            return View();
        }


    }
}

WebApplication2/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{


    public class MoviesController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult List(int? id,string q)
        {

            var movies = MovieRepository.Movies;
            if (id!= null)
            {
                movies = movies.Where(p => p.GenreId == id).ToList();
            }


            //Arama Filtreleme
            if (!string.IsNullOrEmpty(q))
            {
                movies = movies.Where(i => i.Title.ToLower().Contains(q.ToLower())).ToList();
            }

            var model = new MoviesViewModel()
            {
                Movies = movies
                
            };

            return View("Movies",model);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            return View(MovieRepository.GetById(id));
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Genres = new SelectList(GenreRepository.Genres, "GenreId", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Create(Movie m)
        {
           
            //if (ModelState.IsValid)
            //{
                MovieRepository.Add(m);
                return RedirectToAction("List");
            //}
            // ViewBag.Genres = new SelectList(GenreRepository.Genres, "GenreId", "Name");
            //return View(); 
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Genres = new SelectList(GenreRepository.Genres, "GenreId", "Name");
            return View(MovieRepository.GetById(id));
        }

        [HttpPost]
        public IActionResult Edit(Movie m)
        {
            
                MovieRepository.Edit(m);
                return RedirectToAction("Details", "Movies", new { @id = m.MovieId });
            
            //ViewBag.Genres = new SelectList(GenreRepository.Genres, "GenreId", "Name");
            //return View(m); 
        }

        [HttpPost]
        public IActionResult Delete(int MovieId)
        {
            MovieRepository.Delete(MovieId);
            return RedirectToAction("List");
        }
    }
}

WebApplication2/ViewComponents/GenresViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.ViewComponents
{
    public class GenresViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedGenre = RouteData.Values["id"];
            return View(GenreRepository.Genres);
        }
    }
}

WebApplication2/Views/Home/About.cshtml
@model List<Genre>

<p>
    home/about
</p>

@section menu{
    @await Component.InvokeAsync("Genres")
}

WebApplication2/Views/Home/Index.cshtml
@model HomePageViewModel


@section header{
    @await Html.PartialAsync("_header")
}

<body>
    <h1>Movie List</h1>
    @foreach (var movie in Model.PopularMovies)
    {
        @await Html.PartialAsync("_movie",movie)
    }
    
</body>

WebApplication2/Views/Movies/Create.cshtml
@model Movie


<h1>Create A Movie</h1>
<hr />

<form method="post" asp-controller="Movies" asp-action="Create">
    <div class="form-group">
        <label asp-for="Title">Tİtle</label>
        <input asp-for="Title" class="form-control">
        <span asp-validation-for="Title" class="text-danger"></span>
     </div>

    <div class="form-group">
        <label asp-for="Description">Description</label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Director">Director</label>
        <input asp-for="Director" class="form-control">
        <span asp-validation-for="Director" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="ImgUrl">ImgUrl</label>
        <input asp-for="ImgUrl" class="form-control">
        <span asp-validation-for="ImgUrl" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="GenreId"></label>
        <select asp-for="GenreId" class="form-control" asp-items="@ViewBag.Genres">
            <option selected disabled>Seçiniz</option>
        </select>
        <span asp-validation-for="GenreId" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
 </form>

WebApplication2/Views/Movies/Details.cshtml
@model Movie

<div class="card">
    <div class="col-md-3">
        <img src="/img/@Model.ImgUrl" class ="card-img"/>
    </div>
    <div class="col-md-9">
        <div class="card-body">
            <h5 class="card-title">@Model.Title</h5>
            <p class="card-text">@Model.Description</p>
            <p class="card-text">@Model.Director</p>
            @if (@Model.Players !=null)
            {
                <ul>
                    @foreach (var player in @Model.Players)
                    {
                        <li>@player</li>
                    }
                </ul>
            }
        </div>
    </div>
</div>

WebApplication2/Views/Movies/Edit.cshtml
@model Movie


<h1>Edit A Movie</h1>
<hr />

<form method="post" asp-controller="Movies" asp-action="Edit">
    <input type="hidden" name="MovieId" value="@Model.MovieId" />
    <div class="form-group">
        <label asp-for="Title">Title</label>
        <input asp-for="Title" value="@Model.Title" class="form-control">
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Description">Description</label>
        <textarea asp-for="Description" class="form-control">@Model.Description</textarea>
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Director">Director</label>
        <input asp-for="Director" value="@Model.Director" class="form-control">
        <span asp-validation-for="Director" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="ImgUrl">ImgUrl</label>
        <input asp-for="ImgUrl" value="@Model.ImgUrl" class="form-control">
        <span asp-validation-for="ImgUrl" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="GenreId"></label>
        <select asp-for="GenreId" class="form-control" asp-items="@ViewBag.Genres">
            <option selected disabled>Seçiniz</option>
        </select>
        <span asp-validation-for="GenreId" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

WebApplication2/Views/Movies/Index.cshtml
<p>movies</p>

WebApplication2/Views/Movies/Movies.cshtml
@model MoviesViewModel


    <h1>Movie List</h1>
    <div id="Movies">
        @if (Model.Movies.Count>0)
    {
        @foreach (var movie in Model.Movies)
        {
            @await Html.PartialAsync("_movie",movie)
        }
    }
    else
    {
        <div class="alert alert-warning">Film Bulunamadı</div>
    }
</div>
@section menu{
    @*@await Html.PartialAsync("_menu",Model.Genres)*@
    @await Component.InvokeAsync("Genres")
}

WebApplication2/Views/Shared/Components/Genres/Default.cshtml
@model List<Genre>

<div class="list-group">
    <a href="/movies/list" class="list-group-item list-group-item-action @(ViewBag.SelectedGenre == null?"active":"")">All Films</a>
    @foreach (var genre in Model)
    {
        <a href="/movies/list/@genre.GenreId" 
        class="list-group-item list-group-item-action @(ViewBag.SelectedGenre == genre.GenreId.ToString()?"active":"")">@genre.Name</a>

    }
</div>

WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="/css/style.css" rel="stylesheet" />
</head>
<body>
    @await Html.PartialAsync("_navbar")
    @RenderSection("header",false)
    
        <div class="container mt-3">
        @if (IsSectionDefined("menu"))
        {
            <div class="row">
                <div class="col-md-3">
                    @RenderSection("menu" ,false)
                </div>
                <div class="col-md-9">
                    @RenderBody()
                </div>
            </div>
        }

        else
        {
            <div class="row">
                <div class="col-md-12">
                @RenderBody()
                </div>
            </div>
        }

            

            
        </div>
        
   
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>

WebApplication2/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="/css/style.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggler">
                <a href="/home/index" class="mr-2 text-white">Home</a>
                <a href="#" class="-navbar-brand text-white">MovieApp</a>
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a href="/movies/list" class="nav-link">Content</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div>
        @RenderBody()
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>

WebApplication2/Views/Shared/_header.cshtml
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Movie App</h1>
    </div>
</div>

WebApplication2/Views/Shared/_menu.cshtml
@model List<Genre>

<div class="list-group">
    @foreach (var genre in Model)
    {
         <a href="#" class="list-group-item list-group-item-action">@genre.Name</a>
    
    }
</div>

WebApplication2/Views/Shared/_movie.cshtml
@model Movie

<div class="card mb-3" style="max-width: 540px;">
    <div class="row no-gutters">
        <div class="col-md-4">
            <img src="/img/@Model.ImgUrl" class="card-img" alt="@Model.Title">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">@Model.Title</h5>
                    <p>
                    <a asp-controller="Movies" asp-action="Details" asp-route-id="@Model.MovieId" class="btn btn-primary">Details</a>
                        <a asp-controller="Movies" asp-action="Edit" asp-route-id="@Model.MovieId"  class="btn btn-primary">Edit</a>
                    </p>

                    <form asp-controller="Movies" asp-action="Delete" method="post">
                        <input type="hidden" name="MovieId" value="@Model.MovieId"/>
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                
            </div>
        </div>
    </div>
</div>

WebApplication2/Views/Shared/_navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggler">
            <a href="/home/index" class="-navbar-brand text-white">Home</a>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a href="/movies/list" class="nav-link">Movies</a>
                </li>
                <li class="nav-item active">
                    <a href="/movies/create" class="nav-link">Movies-Create</a>
                </li>
            </ul>

            <form action="/movies/list" method="get"  class="form-inline">
                <input type="text" name="q" placeholder="Search a Film" class="form-control mr-2" />
                <button type="submit" class="btn btn-outline-light mr-0 "> Ara </button>
            </form>
        </div>
    </div>
</nav>